/**
 * ABOUTME: Interactive setup wizard for Ralph TUI.
 * Guides users through initial configuration when no .ralph-tui/config.toml exists.
 * Detects available plugins and collects tracker/agent preferences.
 */

import { access, constants, writeFile, mkdir } from 'node:fs/promises';
import { join } from 'node:path';
import { stringify as stringifyToml } from 'smol-toml';
import { getTrackerRegistry } from '../plugins/trackers/registry.js';
import { getAgentRegistry } from '../plugins/agents/registry.js';
import { registerBuiltinTrackers } from '../plugins/trackers/builtin/index.js';
import { registerBuiltinAgents } from '../plugins/agents/builtin/index.js';
import type { StoredConfig } from '../config/types.js';
import type {
  SetupResult,
  SetupOptions,
  SetupAnswers,
  PluginDetection,
} from './types.js';
import {
  promptSelect,
  promptNumber,
  promptBoolean,
  promptQuestion,
  printSection,
  printSuccess,
  printInfo,
  printError,
  isInteractiveTerminal,
} from './prompts.js';
import {
  listBundledSkills,
  isSkillInstalledAt,
  resolveSkillsPath,
  installSkillsForAgent,
} from './skill-installer.js';
import { CURRENT_CONFIG_VERSION } from './migration.js';

/**
 * Config directory and filename
 */
const CONFIG_DIR = '.ralph-tui';
const CONFIG_FILENAME = 'config.toml';

/**
 * Check if a project config file exists
 */
export async function projectConfigExists(cwd: string = process.cwd()): Promise<boolean> {
  const configPath = join(cwd, CONFIG_DIR, CONFIG_FILENAME);
  try {
    await access(configPath, constants.R_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Detect available tracker plugins
 */
async function detectTrackerPlugins(): Promise<PluginDetection[]> {
  const registry = getTrackerRegistry();

  // Register built-in plugins if not already done
  registerBuiltinTrackers();
  await registry.initialize();

  const plugins = registry.getRegisteredPlugins();
  const detections: PluginDetection[] = [];

  for (const meta of plugins) {
    const instance = registry.createInstance(meta.id);
    if (!instance) continue;

    // For trackers, we can't really "detect" without config
    // So we just list them as available
    detections.push({
      id: meta.id,
      name: meta.name,
      description: meta.description,
      available: true,
      version: meta.version,
    });

    await instance.dispose();
  }

  return detections;
}

/**
 * Detect available agent plugins with CLI availability
 */
async function detectAgentPlugins(): Promise<PluginDetection[]> {
  const registry = getAgentRegistry();

  // Register built-in plugins if not already done
  registerBuiltinAgents();
  await registry.initialize();

  const plugins = registry.getRegisteredPlugins();
  const detections: PluginDetection[] = [];

  for (const meta of plugins) {
    const instance = registry.createInstance(meta.id);
    if (!instance) continue;

    // Initialize with empty config to enable detection
    await instance.initialize({});

    // Detect if CLI is available
    const detectResult = await instance.detect();

    detections.push({
      id: meta.id,
      name: meta.name,
      description: meta.description,
      available: detectResult.available,
      version: detectResult.version,
      error: detectResult.error,
    });

    await instance.dispose();
  }

  return detections;
}

/**
 * Collect tracker-specific options via setup questions
 */
async function collectTrackerOptions(
  trackerId: string
): Promise<Record<string, unknown>> {
  const registry = getTrackerRegistry();
  const instance = registry.createInstance(trackerId);
  if (!instance) {
    return {};
  }

  const questions = instance.getSetupQuestions();
  await instance.dispose();

  if (questions.length === 0) {
    return {};
  }

  printSection('트래커 설정');
  printInfo(`${trackerId} 트래커를 설정합니다:`);
  console.log();

  const options: Record<string, unknown> = {};

  for (const question of questions) {
    options[question.id] = await promptQuestion(question);
  }

  return options;
}

/**
 * Save configuration to .ralph-tui/config.toml
 */
async function saveConfig(
  answers: SetupAnswers,
  cwd: string
): Promise<string> {
  const configDir = join(cwd, CONFIG_DIR);
  const configPath = join(configDir, CONFIG_FILENAME);

  // Ensure .ralph-tui directory exists
  await mkdir(configDir, { recursive: true });

  // Build StoredConfig from answers
  const config: StoredConfig = {
    // Config version for future migrations
    configVersion: CURRENT_CONFIG_VERSION,
    // Use shorthand format for simpler config
    tracker: answers.tracker,
    trackerOptions: answers.trackerOptions,
    agent: answers.agent,
    agentOptions: answers.agentOptions,
    maxIterations: answers.maxIterations,
    autoCommit: answers.autoCommit,
  };

  // Serialize to TOML
  const toml = stringifyToml(config);

  // Add header comment
  const content = `# Ralph TUI Configuration
# Generated by setup wizard
# See: ralph-tui config help

${toml}`;

  await writeFile(configPath, content, 'utf-8');

  return configPath;
}

/**
 * Run the interactive setup wizard
 */
export async function runSetupWizard(
  options: SetupOptions = {}
): Promise<SetupResult> {
  const cwd = options.cwd ?? process.cwd();

  try {
    // Check if we're in an interactive terminal
    if (!isInteractiveTerminal()) {
      return {
        success: false,
        error:
          '설정 마법사는 대화형 터미널이 필요합니다. ' +
          '대화형 입력(TTY)을 지원하는 터미널에서 이 명령을 실행해주세요. ' +
          '컨테이너나 자동화 환경에서 실행 중이라면 ' +
          '.ralph-tui/config.toml 설정 파일을 직접 생성하는 것을 고려해주세요.',
      };
    }

    // Check if config already exists
    if (!options.force) {
      const exists = await projectConfigExists(cwd);
      if (exists) {
        return {
          success: false,
          error: `설정 파일이 이미 존재합니다: ${join(cwd, CONFIG_DIR, CONFIG_FILENAME)}. 덮어쓰려면 --force 옵션을 사용하세요.`,
        };
      }
    }

    // Print welcome banner
    console.log();
    console.log('╔════════════════════════════════════════════════════════════╗');
    console.log('║                   Ralph TUI 설정 마법사                      ║');
    console.log('╚════════════════════════════════════════════════════════════╝');
    console.log();
    printInfo('이 마법사가 프로젝트용 Ralph TUI 설정을 도와드립니다.');
    printInfo('언제든지 Ctrl+C를 눌러 취소할 수 있습니다.');

    // === Step 1: Select Tracker ===
    printSection('이슈 트래커 선택');

    const trackerPlugins = await detectTrackerPlugins();
    if (trackerPlugins.length === 0) {
      return {
        success: false,
        error: '사용 가능한 트래커 플러그인이 없습니다. 트래커 플러그인을 설치해주세요.',
      };
    }

    // Build choices with availability info
    const trackerChoices = trackerPlugins.map((p) => ({
      value: p.id,
      label: p.name,
      description: p.available
        ? p.description
        : `${p.description} (not available: ${p.error})`,
    }));

    const selectedTracker = await promptSelect(
      '어떤 이슈 트래커를 사용하시겠습니까?',
      trackerChoices,
      {
        default: trackerPlugins.find((p) => p.available)?.id,
        help: 'Ralph가 이 트래커를 사용하여 작업을 관리합니다.',
      }
    );

    // Collect tracker-specific options
    const trackerOptions = await collectTrackerOptions(selectedTracker);

    // === Step 2: Select Agent ===
    printSection('에이전트 CLI 선택');

    const agentPlugins = await detectAgentPlugins();
    if (agentPlugins.length === 0) {
      return {
        success: false,
        error: '사용 가능한 에이전트 플러그인이 없습니다. 에이전트 플러그인을 설치해주세요.',
      };
    }

    // Build choices with availability info
    const agentChoices = agentPlugins.map((p) => ({
      value: p.id,
      label: `${p.name}${p.available ? ` (v${p.version})` : ''}`,
      description: p.available
        ? p.description
        : `${p.description} (not detected: ${p.error})`,
    }));

    // Find first available agent as default
    const defaultAgent = agentPlugins.find((p) => p.available)?.id;

    printInfo('Ralph는 여러 AI 코딩 에이전트를 지원합니다.');
    if (defaultAgent) {
      printSuccess(`자동 감지됨: ${agentPlugins.find((p) => p.id === defaultAgent)?.name}`);
    }
    console.log();

    const selectedAgent = await promptSelect(
      '어떤 에이전트 CLI를 사용하시겠습니까?',
      agentChoices,
      {
        default: defaultAgent,
        help: '코딩 작업을 실행할 AI 에이전트입니다.',
      }
    );

    // Collect agent-specific options (skip for default setup)
    // For simplicity, we'll skip agent-specific options in the wizard
    // They can be configured later via config file
    const agentOptions: Record<string, unknown> = {};

    // === Step 3: Iteration Settings ===
    printSection('반복 설정');

    const maxIterations = await promptNumber(
      '실행당 최대 반복 횟수는?',
      {
        default: 10,
        min: 0,
        max: 1000,
        help: '중지하기 전에 처리할 작업 수 (0 = 무제한).',
      }
    );

    const autoCommit = await promptBoolean(
      '작업 완료 시 자동 커밋?',
      {
        default: false,
        help: '각 작업이 성공적으로 완료된 후 자동으로 변경사항을 커밋합니다.',
      }
    );

    // === Step 4: Skills Installation ===
    printSection('AI 스킬 설치');

    // Get the selected agent's skills paths from the registry
    const agentRegistry = getAgentRegistry();
    const agentMeta = agentRegistry.getPluginMeta(selectedAgent);
    const skillsPaths = agentMeta?.skillsPaths;

    if (!skillsPaths) {
      printInfo(`에이전트 "${agentMeta?.name ?? selectedAgent}"는 스킬 설치를 지원하지 않습니다.`);
    } else {
      const bundledSkills = await listBundledSkills();

      if (bundledSkills.length > 0) {
        const personalDir = resolveSkillsPath(skillsPaths.personal);
        printInfo('Ralph TUI에는 에이전트 기능을 향상시키는 AI 스킬이 포함되어 있습니다.');
        printInfo(`스킬 설치 위치: ${personalDir}`);
        console.log();

        for (const skill of bundledSkills) {
          const alreadyInstalled = await isSkillInstalledAt(skill.name, personalDir);
          const actionLabel = alreadyInstalled ? '업데이트' : '설치';

          const installThisSkill = await promptBoolean(
            `스킬 ${actionLabel}: ${skill.name}?`,
            {
              default: true,
              help: alreadyInstalled
                ? `${skill.description} (현재 설치됨 - 최신 버전으로 업데이트)`
                : skill.description,
            }
          );

          if (installThisSkill) {
            const result = await installSkillsForAgent(
              selectedAgent,
              agentMeta?.name ?? selectedAgent,
              skillsPaths,
              { force: true, personal: true, repo: false, skillName: skill.name }
            );

            // Report results from the agent-specific installation
            const skillResults = result.skills.get(skill.name);
            const personalResult = skillResults?.find(r => r.target === 'personal');
            if (personalResult?.result.success) {
              printSuccess(`  ${alreadyInstalled ? '업데이트됨' : '설치됨'}: ${skill.name}`);
              if (personalResult.result.path) {
                printInfo(`    위치: ${personalResult.result.path}`);
              }
            } else {
              const error = personalResult?.result.error ?? '알 수 없는 오류';
              printError(`  ${skill.name} ${actionLabel} 실패: ${error}`);
            }
          } else if (alreadyInstalled) {
            printInfo(`  ${skill.name}: 기존 버전 유지`);
          }
        }
      } else {
        printInfo('설치 가능한 번들 스킬이 없습니다.');
      }
    }

    // === Save Configuration ===
    const answers: SetupAnswers = {
      tracker: selectedTracker,
      trackerOptions,
      agent: selectedAgent,
      agentOptions,
      maxIterations,
      autoCommit,
    };

    printSection('설정 저장');

    const configPath = await saveConfig(answers, cwd);

    console.log();
    printSuccess(`설정이 저장되었습니다: ${configPath}`);
    console.log();

    // === Verify Agent Configuration ===
    printSection('에이전트 설정 검증');

    printInfo('에이전트 사전 검사 실행 중...');
    console.log();

    // Get a fresh agent instance with the configured options
    const agentInstance = await agentRegistry.getInstance({
      name: selectedAgent,
      plugin: selectedAgent,
      options: agentOptions,
    });

    // Run preflight check
    const preflightResult = await agentInstance.preflight({ timeout: 30000 });

    if (preflightResult.success) {
      printSuccess(`✓ 에이전트가 올바르게 설정되어 응답 중입니다`);
      if (preflightResult.durationMs) {
        printInfo(`  응답 시간: ${preflightResult.durationMs}ms`);
      }
      console.log();
    } else {
      printError(`✗ 에이전트 사전 검사 실패`);
      if (preflightResult.error) {
        printError(`  ${preflightResult.error}`);
      }
      if (preflightResult.suggestion) {
        console.log();
        printInfo('제안사항:');
        // Split suggestion by newlines and print each line
        for (const line of preflightResult.suggestion.split('\n')) {
          console.log(`  ${line}`);
        }
      }
      console.log();
      printInfo('설정이 저장되었지만 에이전트가 응답하지 않습니다.');
      printInfo('"ralph-tui doctor"를 실행하여 문제를 진단하세요.');
      console.log();
    }

    // Show tracker-specific instructions
    if (selectedTracker === 'json') {
      printInfo('이제 다음 명령으로 Ralph TUI를 실행할 수 있습니다:');
      console.log();
      console.log('  PRD와 작업 생성:               ralph-tui create-prd');
      console.log('  기존 작업으로 Ralph 실행:      ralph-tui run --prd <prd.json 경로>');
    } else {
      printInfo('이제 다음 명령으로 Ralph TUI를 실행할 수 있습니다:');
      console.log();
      console.log('  ralph-tui run');
    }
    console.log();
    printInfo('또는 다음 명령으로 설정을 확인할 수 있습니다:');
    console.log();
    console.log('  ralph-tui config show');
    console.log();

    return {
      success: true,
      answers,
      configPath,
    };
  } catch (error) {
    // Check for user cancellation (Ctrl+C)
    if (error instanceof Error && error.message.includes('readline was closed')) {
      console.log();
      printInfo('설정이 취소되었습니다.');
      return {
        success: false,
        cancelled: true,
      };
    }

    return {
      success: false,
      error: error instanceof Error ? error.message : String(error),
    };
  }
}

/**
 * Check if setup is needed and optionally run the wizard
 */
export async function checkAndRunSetup(
  options: SetupOptions & { skipSetup?: boolean } = {}
): Promise<SetupResult | null> {
  const cwd = options.cwd ?? process.cwd();

  // Check if config exists
  const exists = await projectConfigExists(cwd);

  if (exists) {
    // Config exists, no setup needed
    return null;
  }

  if (options.skipSetup) {
    // User wants to skip setup
    printInfo('설정을 찾을 수 없습니다. "ralph-tui setup"을 실행하여 설정을 생성하세요.');
    return null;
  }

  // Run the wizard
  return runSetupWizard(options);
}
